/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioclg;

import java.sql.*;
import oracle.jdbc.pool.*;

/**
 *
 * @author Francis
 */
public class Emprunt extends javax.swing.JFrame {

    /**
     * Creates new form Emprunt
     */
    Connection conn1=null;
    Connection conn2=null;
    Statement stm2=null;
    ResultSet rset2=null;
    Statement stm1=null;
        ResultSet rset1=null;
    public Emprunt() {
        conn1 = BiblioClg.MakeConnection();
        conn2 = BiblioClg.MakeConnection();
        initComponents();
        fillPersonne();
        fillLivre();
        
    }
    
    private void fillLivre(){
        
        String sql = "select NUMLIVRE,Titre from livre";
        
        
        try {
            
            stm2 = conn2.createStatement( ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            rset2 = stm2.executeQuery(sql);
            
            Cb_Livre.removeAllItems();
            while(rset2.next())//{
                Cb_Livre.addItem(new ComboItem(rset2.getString(2), rset2.getString(1)));
            
//            System.out.println(rset2.getString(2));}
//            System.out.println(Cb_Livre.getSelectedObjects().toString());
            
            
        } catch (Exception e) {
            System.out.println("Erreur Fillset: "+e.getMessage());
        }
        finally{
            
            
            
        }
    }
    private void fillPersonne(){
        
        String sql = "select * from ADHERENT";
        
        try {
            
            stm1 = conn1.createStatement( ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            rset1 = stm1.executeQuery(sql);
            
            Cb_Personne.removeAllItems();
            while(rset1.next())
                Cb_Personne.addItem(new ComboItem(rset1.getString(3)+" "+rset1.getString(2), rset1.getString(1)));
            
            //System.out.println(rset.getString(2));
            
            
            
        } catch (Exception e) {
            System.out.println("Erreur Fillset: "+e.getMessage());
        }
        finally{
            
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cb_Livre = new javax.swing.JComboBox();
        Cb_Personne = new javax.swing.JComboBox();
        Bt_Emprunter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        Cb_Livre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Cb_Personne.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Bt_Emprunter.setText("Emprunter");
        Bt_Emprunter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_EmprunterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Cb_Personne, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Cb_Livre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bt_Emprunter, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Cb_Livre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(Cb_Personne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(Bt_Emprunter)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bt_EmprunterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_EmprunterActionPerformed
        Connection conn3 = BiblioClg.MakeConnection();
        String sql = "{call GESTIONLIVRE.AJOUTER(?,?)}";
        CallableStatement callstm = null;
        ResultSet rset=null;
        try {
            callstm = conn3.prepareCall(sql);
            rset2.absolute(Cb_Livre.getSelectedIndex()+1);
            System.out.println(rset2.getInt(1));
            callstm.setInt(1, rset2.getInt(1));
            rset1.absolute(Cb_Personne.getSelectedIndex()+1);
            callstm.setInt(2, rset1.getInt(1));
            callstm.executeUpdate();
            
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        finally{
            try {
                callstm.close();
                conn2.close();
            } catch (Exception e) {
            }
    }        // TODO add your handling code here:
    }//GEN-LAST:event_Bt_EmprunterActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        try {
                rset1.close();
                stm1.close();
            } catch (Exception e) {
            }
        try {
                rset2.close();
                stm2.close();
            } catch (Exception e) {
            }
                    // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Emprunt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Emprunt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Emprunt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Emprunt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Emprunt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_Emprunter;
    private javax.swing.JComboBox Cb_Livre;
    private javax.swing.JComboBox Cb_Personne;
    // End of variables declaration//GEN-END:variables
}
