/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioclg;

import java.sql.*;
import oracle.jdbc.internal.OracleTypes;
import oracle.jdbc.oracore.OracleType;
import oracle.jdbc.pool.*;

/**
 *
 * @author Francis
 */
public class User extends javax.swing.JFrame {

    /**
     * Creates new form User
     */
    
    
    
    ResultSet rset;
    Statement stm ;
    Connection conn;
    
    
    
    public User() {
        conn = BiblioClg.MakeConnection();
       
        initComponents();
        refreshData();
        
        
    }
    
    private void FillSet(){
        
        String sql = "select * from ADHERENT";
        
        try {
            
            stm = conn.createStatement( ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            rset = stm.executeQuery(sql);
            rset.next();
            System.out.println(rset.getString(2));
            
            
            
        } catch (Exception e) {
            System.out.println("Erreur Fillset: "+e.getMessage());
        }
        finally{
            
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Tb_Nom = new javax.swing.JTextField();
        Tb_Prenom = new javax.swing.JTextField();
        Tb_Adresse = new javax.swing.JTextField();
        Tb_Tel = new javax.swing.JTextField();
        Bt_Vider = new javax.swing.JButton();
        Bt_Prec = new javax.swing.JButton();
        Bt_Suiv = new javax.swing.JButton();
        Bt_MAJ = new javax.swing.JButton();
        Bt_Creer = new javax.swing.JButton();
        Bt_Supp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adhérent");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Nom:");

        jLabel3.setText("Prenom:");

        jLabel5.setText("Adresse:");

        jLabel6.setText("Téléphone:");

        Tb_Nom.setText("Tb_Nom");
        Tb_Nom.setName("Tb_Nom"); // NOI18N

        Tb_Prenom.setText("Tb_Prenom");
        Tb_Prenom.setName("Tb_Prenom"); // NOI18N

        Tb_Adresse.setText("Tb_Adresse");
        Tb_Adresse.setName("Tb_Adresse"); // NOI18N

        Tb_Tel.setText("Tb_Tel");
        Tb_Tel.setName("Tb_Tel"); // NOI18N

        Bt_Vider.setText("Vider");
        Bt_Vider.setName("Bt_Vider"); // NOI18N
        Bt_Vider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_ViderActionPerformed(evt);
            }
        });

        Bt_Prec.setText("Précédent");
        Bt_Prec.setName("Bt_Prec"); // NOI18N
        Bt_Prec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_PrecActionPerformed(evt);
            }
        });

        Bt_Suiv.setLabel("Suivant");
        Bt_Suiv.setName("Bt_Suivant"); // NOI18N
        Bt_Suiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_SuivActionPerformed(evt);
            }
        });

        Bt_MAJ.setText("M. à J.");
        Bt_MAJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_MAJActionPerformed(evt);
            }
        });

        Bt_Creer.setText("Créer");
        Bt_Creer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_CreerActionPerformed(evt);
            }
        });

        Bt_Supp.setText("Supprimer");
        Bt_Supp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_SuppActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Bt_Prec, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                        .addGap(7, 7, 7)
                        .addComponent(Bt_Suiv, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel5))
                            .addComponent(jLabel6))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tb_Adresse, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tb_Tel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Bt_Creer, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bt_Supp)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel3)
                        .addGap(5, 5, 5)
                        .addComponent(Tb_Prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Bt_MAJ, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1)
                        .addGap(5, 5, 5)
                        .addComponent(Tb_Nom, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Bt_Vider, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addComponent(Tb_Nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bt_Vider))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Tb_Prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(Bt_MAJ))))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Tb_Adresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(Tb_Tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(Bt_Creer)
                        .addGap(4, 4, 4)
                        .addComponent(Bt_Supp)))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Bt_Suiv)
                    .addComponent(Bt_Prec))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Tb_Nom.getAccessibleContext().setAccessibleName("Tb_Nom");
        Tb_Prenom.getAccessibleContext().setAccessibleName("Tb_Prenom");
        Tb_Adresse.getAccessibleContext().setAccessibleName("Tb_Adresse");
        Tb_Tel.getAccessibleContext().setAccessibleName("Tb_Tel");
        Bt_Prec.getAccessibleContext().setAccessibleName("Bt_Prec");
        Bt_Suiv.getAccessibleContext().setAccessibleName("Bt_Suivant");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FillBox(){
       
        if (rset != null) {
            try {
                
                Tb_Nom.setText(rset.getString(2));
                Tb_Prenom.setText(rset.getString(3));
                Tb_Adresse.setText(rset.getString(4));
                Tb_Tel.setText(rset.getString(5));
                
            } catch (Exception e) {
                System.out.println("Shit appen:"+e.getMessage());
            }
            
        }
    }
    
    private void refreshData(){
        FillSet();
        try{
            rset.first();
            if (rset.isFirst()) {
                Bt_Prec.setEnabled(false);
            }
            else{
                Bt_Prec.setEnabled(true);
            }
            if (rset.isLast()) {
                Bt_Suiv.setEnabled(false);
            }
            else{
                 Bt_Suiv.setEnabled(true);
            }
        }catch (Exception ex) {}
       
        FillBox();
        
    }
    
    private void Bt_ViderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_ViderActionPerformed
            Tb_Nom.setText("");
            Tb_Prenom.setText("");
            Tb_Adresse.setText("");
            Tb_Tel.setText("");
    }//GEN-LAST:event_Bt_ViderActionPerformed

    private void Bt_SuivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_SuivActionPerformed
        try {
            
                rset.next();
                Bt_Prec.setEnabled(true);
                FillBox();
            
            if(rset.isLast())
                Bt_Suiv.setEnabled(false);
        } catch (Exception e) {
             System.out.println("Shit appen:"+e.getMessage());
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_Bt_SuivActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
       try
        {
            if (conn!=null)
                conn.close();
            System.out.println("connexion fermée");
        }
        catch(SQLException se){
        System.out.println("connexion fermée");
        } // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void Bt_PrecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_PrecActionPerformed
       try {
            
                rset.previous();
                Bt_Suiv.setEnabled(true);
                FillBox();
            
            if(rset.isFirst())
                Bt_Prec.setEnabled(false);
        } catch (Exception e) {
             System.out.println("Shit appen:"+e.getMessage());
        } // TODO add your handling code here:
    }//GEN-LAST:event_Bt_PrecActionPerformed

    private void Bt_MAJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_MAJActionPerformed
        Connection conn2 = BiblioClg.MakeConnection();
        String sql = "{call GESTIONADHERENT.MODIFIER(?,?,?,?,?)}";
        CallableStatement callstm = null;
        try {
             callstm = conn2.prepareCall(sql);
            callstm.setInt(1, rset.getInt(1));
            callstm.setString(2, Tb_Nom.getText());
            callstm.setString(3, Tb_Prenom.getText());
            callstm.setString(4, Tb_Adresse.getText());
            callstm.setString(5, Tb_Tel.getText());
            callstm.executeUpdate();
            refreshData();
        } catch (Exception e) {
        }
        finally{
            try {
                callstm.close();
                conn2.close();
            } catch (Exception e) {
            }
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_Bt_MAJActionPerformed

    private void Bt_CreerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_CreerActionPerformed
           Connection conn2 = BiblioClg.MakeConnection();
        String sql = "{call GESTIONADHERENT.INSERTION(?,?,?,?)}";
        CallableStatement callstm = null;
        try {
             callstm = conn.prepareCall(sql);
            callstm.setString(1, Tb_Nom.getText());
            callstm.setString(2, Tb_Prenom.getText());
            callstm.setString(3, Tb_Adresse.getText());
            callstm.setInt(4, Integer.parseInt( Tb_Tel.getText()));
            callstm.executeUpdate();
            refreshData();
        } catch (Exception e) {
        }
        finally{
            try {
                callstm.close();
                conn2.close();
            } catch (Exception e) {
            }
    }
    }//GEN-LAST:event_Bt_CreerActionPerformed

    private void Bt_SuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_SuppActionPerformed
        Connection conn2 = BiblioClg.MakeConnection();
        String sql = "{call GESTIONADHERENT.SUPPRIMER(?)}";
        CallableStatement callstm = null;
        try {
             callstm = conn.prepareCall(sql);
            callstm.setInt(1, rset.getInt(1));
            callstm.executeUpdate();
            refreshData();
        } catch (Exception e) {
        }
        finally{
            try {
                callstm.close();
                conn2.close();
            } catch (Exception e) {
            }
    } 
    }//GEN-LAST:event_Bt_SuppActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_Creer;
    private javax.swing.JButton Bt_MAJ;
    private javax.swing.JButton Bt_Prec;
    private javax.swing.JButton Bt_Suiv;
    private javax.swing.JButton Bt_Supp;
    private javax.swing.JButton Bt_Vider;
    private javax.swing.JTextField Tb_Adresse;
    private javax.swing.JTextField Tb_Nom;
    private javax.swing.JTextField Tb_Prenom;
    private javax.swing.JTextField Tb_Tel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
